import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlassProvider from 'glass-js'
const inter = Inter({ subsets: ["latin"] });

export const revalidate = 0;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <GlassProvider>{children}</GlassProvider></body>
    </html>
  );
}
